# Generated by Django 5.0.4 on 2024-04-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='paymentType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
