# Generated by Django 5.0.4 on 2024-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='last_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
